---
all:
  children:
    boat_nodes:
      hosts:
        boat-node:
          ansible_host: boat-node.local
          ansible_user: fkimn3rd
      vars:
        ansible_python_interpreter: /usr/bin/python3
