---
all:
  children:
    boat_nodes:
      hosts:
        boat-node:
          # IP dell'hotspot iPhone in fase di sviluppo — da aggiornare quando
          # il Pi sarà sulla rete di bordo (vedi README).
          ansible_host: 172.20.10.6
          ansible_user: fkimn3rd
      vars:
        ansible_python_interpreter: /usr/bin/python3
